gcp_project_id      = "data-eng-zcamp-liminm"
gcs_bucket_name     = "data-eng-zcamp-liminm-bucket"
bq_dataset_name     = "data_eng_zcamp_liminm_bq_bucket"
service_account_name = "l6194005"
airflow_db_password = "really-strong-pw"